version: "3.7"

services:
  
  wildfly-setup:
    image: docker/compose:1.24.1
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: ./docker-compose.yml
        target: /docker-compose.yml
      - type: bind
        source: ./.env
        target: /.env
    entrypoint: ""
    command:
      - /bin/sh
      - -ce
      - |
        docker-compose ps
        echo "wait for precondition..."
        ( docker-compose logs --follow --tail 2 wildfly & ) | grep -q 'Admin console listening'
        echo "precondition matched, continue..."

        echo "wildfly server state"
        docker-compose exec -T wildfly /opt/jboss/wildfly/bin/jboss-cli.sh --connect --command=":read-attribute(name=server-state)"
        echo wildfly product info
        docker-compose exec -T wildfly /opt/jboss/wildfly/bin/jboss-cli.sh --connect --command=":product-info()"

        echo "download keycloak adapter"
        docker-compose exec -T -w /opt/jboss/wildfly wildfly /bin/bash -c "curl -L https://downloads.jboss.org/keycloak/$KEYCLOAK_VERSION/adapters/keycloak-oidc/keycloak-wildfly-adapter-dist-$KEYCLOAK_VERSION.tar.gz | tar zx"
        echo "install keycloak adapter"
        docker-compose exec -T -w /opt/jboss/wildfly wildfly cp -a modules/system/add-ons/keycloak/org/keycloak modules/system/layers/base/org/
        docker-compose exec -T -w /opt/jboss/wildfly wildfly /opt/jboss/wildfly/bin/jboss-cli.sh --connect --file=./bin/adapter-elytron-install.cli

        echo "download postgres module"
        docker-compose exec -T -w /tmp wildfly /bin/bash -c "curl -L https://jdbc.postgresql.org/download/postgresql-$POSTGRES_VERSION.jar -O"
        echo "install postgres module"
        docker-compose exec -T wildfly /opt/jboss/wildfly/bin/jboss-cli.sh --connect << EOF
        # Add PostgreSQL module (generate modules/org/postgresql/jdbc/main/module.xml)
        module add --name=org.postgresql.jdbc --resources=/tmp/postgresql-$POSTGRES_VERSION.jar --dependencies=javax.api,javax.transaction.api
        # Add PostgreSQL driver (to standalone.xml)
        /subsystem=datasources/jdbc-driver=postgres:add(driver-name="postgres",driver-module-name="org.postgresql.jdbc",driver-class-name=org.postgresql.Driver,driver-xa-datasource-class-name=org.postgresql.xa.PGXADataSource)
        EOF

        echo "reload wildfly"
        docker-compose exec -T wildfly /opt/jboss/wildfly/bin/jboss-cli.sh --connect --command=":reload()"
        echo wildfly server state
        docker-compose exec -T wildfly /opt/jboss/wildfly/bin/jboss-cli.sh --connect --command=":read-attribute(name=server-state)"

        echo "docker-compose service 'wildfly-setup' finished."
    depends_on:
      - wildfly
